// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oo7KTrTzZMONL0zMsOhnbo-dB_gby3A',
    appId: '1:180208529198:web:192811974887dac95c94bf',
    messagingSenderId: '180208529198',
    projectId: 'lexus-f6fa7',
    authDomain: 'lexus-f6fa7.firebaseapp.com',
    storageBucket: 'lexus-f6fa7.firebasestorage.app',
    measurementId: 'G-W224WPW2NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxt4uk2G3h-yDQ5rjyC_IRI8E-kYC2d0',
    appId: '1:180208529198:android:c172857c7f4c672a5c94bf',
    messagingSenderId: '180208529198',
    projectId: 'lexus-f6fa7',
    storageBucket: 'lexus-f6fa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8nfO9fJvPrYce49eDdjFe-X0UDvqUUU',
    appId: '1:180208529198:ios:a2ef741faf132e315c94bf',
    messagingSenderId: '180208529198',
    projectId: 'lexus-f6fa7',
    storageBucket: 'lexus-f6fa7.firebasestorage.app',
    iosBundleId: 'com.example.rahim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8nfO9fJvPrYce49eDdjFe-X0UDvqUUU',
    appId: '1:180208529198:ios:a2ef741faf132e315c94bf',
    messagingSenderId: '180208529198',
    projectId: 'lexus-f6fa7',
    storageBucket: 'lexus-f6fa7.firebasestorage.app',
    iosBundleId: 'com.example.rahim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2oo7KTrTzZMONL0zMsOhnbo-dB_gby3A',
    appId: '1:180208529198:web:3e1c87cce9b2db475c94bf',
    messagingSenderId: '180208529198',
    projectId: 'lexus-f6fa7',
    authDomain: 'lexus-f6fa7.firebaseapp.com',
    storageBucket: 'lexus-f6fa7.firebasestorage.app',
    measurementId: 'G-ES7ZTHLG9C',
  );
}
